Threads=12
SoXDir=/usr/bin/sox
CamillaDSPDir=/usr/bin/camilladsp
DebugFile=/var/log/debug.log
PreProcessGain=-2
Normalize=0
UseMultipleConvolutionFiles=true
UseMaxResamplerQuality=true
ConvolutionFileFormat=FLOAT64LE
CompressionLevel=8
MaxSampleRate=384000
MaxDSDSampleRate=DSD128
